services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 20anniversary
      POSTGRES_DB: thanksgiving
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
  
  upload-server:
    build: .
    command: uvicorn upload:app --host 0.0.0.0 --port 5000
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 20anniversary
      POSTGRES_DB: thanksgiving
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  
  display-server:
    build: .
    command: uvicorn display:app --host 0.0.0.0 --port 5001
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 20anniversary
      POSTGRES_DB: thanksgiving
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5001:5001"
    depends_on:
      - postgres

volumes:
  pg_data:
